# Generated by Django 6.0.3 on 2026-06-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_alter_carro_placa_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('ELE', 'Elétrica'), ('MEC', 'Mecânica'), ('HID', 'Hidráulica'), ('BAL', 'Balanceamento'), ('TRP', 'Troca de Pneus'), ('REP', 'Revisão Preventiva'), ('RPR', 'Revisão Programada'), ('FUN', 'Funilaria'), ('PIN', 'Pintura'), ('FRE', 'Freios'), ('SUS', 'Suspensão'), ('CAM', 'Câmbio'), ('MOT', 'Motor'), ('ARC', 'Ar Condicionado'), ('ESC', 'Escapamento'), ('VIS', 'Vistoria'), ('OUT', 'Outros')], max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(null=True)),
                ('data_entrega', models.DateField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('protocolo', models.CharField(blank=True, max_length=30, null=True)),
                ('categoria_manutecao', models.ManyToManyField(to='servicos.categoriamanutencao')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
