# Generated by Django 6.0.4 on 2026-06-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_protocolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='categoria_manutecao',
            new_name='categoria_manutencao',
        ),
    ]
