# Generated by Django 6.0.4 on 2026-05-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carros',
            new_name='Carro',
        ),
        migrations.RenameField(
            model_name='carro',
            old_name='lavagem',
            new_name='lavagens',
        ),
    ]
