# Generated by Django 6.0.4 on 2026-05-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_carros_carro_rename_lavagem_carro_lavagens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='Cliente',
            new_name='cliente',
        ),
    ]
